services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
    - ./migrations:/app/migrations
    - ./scripts:/app/scripts
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: taskuser
      DB_PASSWORD: taskpass
      DB_NAME: taskdb
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "/app/scripts/migrate.sh; /app/task-manager"

volumes:
  postgres_data: